services:
  - type: web
    name: siscon-ap
    env: node
    buildCommand: |
      npm config set registry https://registry.npmjs.org/
      npm config set @gridstack:registry https://registry.npmjs.org/
      npm install --legacy-peer-deps
      npm run build
    startCommand: node server.js
    envVars:
      - key: NODE_VERSION
        value: 18.x
      - key: NPM_CONFIG_REGISTRY
        value: "https://registry.npmjs.org/"
      - key: NPM_CONFIG_LEGACY_PEER_DEPS
        value: "true"
      - key: NPM_CONFIG_AUDIT
        value: "false"
      - key: NPM_CONFIG_FUND
        value: "false"
      - key: NPM_CONFIG_UPDATE_NOTIFIER
        value: "false"
      - key: NPM_CONFIG_PREFER_OFFLINE
        value: "true"
    plan: free
