# Generated by Django 5.2 on 2025-04-21 10:35

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rubro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Código único identificador del rubro (ej. 2111)', max_length=50, unique=True, verbose_name='Código del Rubro')),
                ('nombre', models.CharField(help_text='Nombre descriptivo del rubro presupuestal', max_length=255, verbose_name='Nombre del Rubro')),
                ('monto_inicial', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Presupuesto inicial asignado al rubro', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Monto Inicial')),
            ],
            options={
                'verbose_name': 'Rubro Presupuestal',
                'verbose_name_plural': 'Rubros Presupuestales',
                'ordering': ['codigo'],
            },
        ),
    ]
